apiVersion: rbac.authorization.k8s.io/v1
kind: [[ forms[0].isClusterRole ? "ClusterRole" : "Role"]]
metadata:
  name: [[forms[0].name]]
[[ !forms[0].isClusterRole && forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
rules:
  - apiGroups:
      - [[forms[0].apiGroup]]
    resources:
      - [[ forms[0].resources.join("\n      - ") ]]
    verbs:
      - [[ forms[0].verbs.join("\n      - ") ]]