apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: [[forms[0].serviceAccountName]]-[[forms[0].targetRole]]-binding
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
subjects:
- kind: ServiceAccount
  name: [[ forms[0].serviceAccountName ]]
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: [[ forms[0].targetRole ]]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: [[ forms[0].serviceAccountName ]]
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
