apiVersion: rbac.authorization.k8s.io/v1
kind: [[ forms[0].isClusterRole ? "ClusterRoleBinding" : "RoleBinding"]]
metadata:
  name: [[forms[0].serviceAccountName]]-[[forms[0].isClusterRole ? forms[0].targetClusterRole : forms[0].targetRole]]-binding
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
subjects:
- kind: ServiceAccount
  name: [[ forms[0].serviceAccountName ]]
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: [[ forms[0].isClusterRole ? "ClusterRole" : "Role"]]
  name: [[ forms[0].isClusterRole ? forms[0].targetClusterRole : forms[0].targetRole ]]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: [[ forms[0].serviceAccountName ]]
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
