apiVersion: batch/v1
kind: Job
metadata:
  name: [[forms[0].name]]
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
spec:
  template:
    spec:
      containers:
        - image: [[forms[0].image]]
          name: [[forms[0].name]]
          resources: {}
          command:
            - [[forms[0].command]]
      restartPolicy: Never
